language: objective-c
xcode_project: Project/WFColorCode.xcodeproj
xcode_scheme: ColorCodeTests
osx_image: xcode8

# coveralls
before_install:
  - sudo easy_install cpp-coveralls
script: xctool -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME" test TEST_AFTER_BUILD=YES OBJROOT=build GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - coveralls -e ColorCodeTests
