name: Test

on: [push, pull_request]

jobs:
  macOS:
    name: Test on macOS
    runs-on: macos-13
    steps:
    - name: Show environments
      run: |
        swift --version
        xcodebuild -version
    - uses: actions/checkout@v1
    - name: Lint Swift
      run: |
        swiftlint
    - name: Test SwiftPM
      run: |
        swift build
        swift test 2>&1 | xcpretty -c
