name: Test

on: [push, pull_request]

jobs:
  macOS:
    name: Test on macOS
    runs-on: macos-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.0.app
    steps:
    - name: Show environments
      run: |
        swift --version
        xcodebuild -version
    - uses: actions/checkout@v4
    - name: Unit Test
      run: |
        swift test --enable-swift-testing
